using UnityEngine;

namespace Cainos.PixelArtPlatformer_VillageProps
{
    public class Elevator : MonoBehaviour
    {
        private Vector2 lengthRange = new Vector2(2, 5);
        private float waitTime = 1.0f;
        private float moveSpeed = 3.0f;
        private State startState = State.Up;

        private Rigidbody2D platform;
        private SpriteRenderer chainL;
        private SpriteRenderer chainR;
        
        public float Length
        {
            get { return length; }
            set
            {
                if (value < 0) value = 0.0f;
                this.length = value;

                platform.transform.localPosition = new Vector3(0.0f, -value, 0.0f);
                chainL.size = new Vector2(0.09375f, value - 8 * 0.03125f );
                chainR.size = new Vector2(0.09375f, value - 8 * 0.03125f );
            }
        }
        private float length;
        
        public State CurState
        {
            get { return curState; }
            set
            {
                curState = value;
            }
        }
        private State curState;

        
        public bool IsWaiting
        {
            get { return isWaiting; }
            set
            {
                if (isWaiting == value) return;
                isWaiting = value;
                waitTimer = 0.0f;
            }
        }
        private bool isWaiting = false;


        private float waitTimer;
        private float curSpeed;
        private float targetLength;
        //private SecondOrderDynamics secondOrderDynamics = new SecondOrderDynamics(4.0f, 0.3f, -0.3f);


        private void Start()
        {
            curState = startState;
            Length = curState == State.Up ? lengthRange.y : lengthRange.x;
            targetLength = Length;

            //secondOrderDynamics.Reset(targetLength);
        }

        private void Update()
        {
            if (IsWaiting)
            {
                waitTimer += Time.deltaTime;
                if (waitTimer > waitTime) IsWaiting = false;
                curSpeed = 0.0f;
            }
            else
            {
                if (curState == State.Up)
                {
                    curSpeed = -moveSpeed;
                    if (targetLength < lengthRange.x)
                    {
                        curState = State.Down;
                        IsWaiting = true;
                    }
                }
                else if (curState == State.Down)
                {
                    curSpeed = moveSpeed;
                    if (targetLength > lengthRange.y)
                    {
                        curState = State.Up;
                        IsWaiting = true;
                    }
                }
            }

            targetLength += curSpeed * Time.deltaTime;
        }

        private void FixedUpdate()
        {
            //Length = secondOrderDynamics.Update(targetLength, Time.fixedDeltaTime);
        }

        public enum State
        {
            Up,
            Down
        }
    }
}

